### ISSUE TITLE
Error after update to  455.28 

### ISSUE THREAD

**Issue by pablomenino** [negativo17/nvidia-driver#104]
I update the nvidia package to 455.28 (dnf update) 

Can't boot into graphical mode, 

I try to remove and install again with dkms, try to boot older kernels. And nothing. 

I can't catch the error

I am on KDE, kernel 5.8.14-200

Any way to rollback to version 450.80.02

I try with dnf - - showduplicates, but only see the last nvidia package.

**Comment by pablomenino** [comment]
after remove nvidia driver the system is working with Nouveau

**Comment by h3o66** [comment]
Did you install the driver with dkms or akmod ?

**Comment by pablomenino** [comment]
dkms

sudo dnf install nvidia-settings kernel-devel dkms-nvidia nvidia-driver-libs.i686 vulkan-loader.x86_64 vulkan-loader.i686

**Comment by pablomenino** [comment]
Solved after migrated to RPM Fusion driver package
