### ISSUE TITLE
Random driver crashes when memory usage is high

### ISSUE THREAD

**Issue by luk1337** [negativo17/nvidia-driver#107]
Hey, recently nvidia put up some diffs in this thread https://forums.developer.nvidia.com/t/455-23-04-page-allocation-failure-in-kernel-module-at-random-points/155250, would it be possible to have this driver patched by default so that affected users won't need to do it themselves?

**Comment by scaronni** [comment]
Sounds good. Building it now, if tests are fine I'll push it to the repos.
