### ISSUE TITLE
Version 470.42.01 has been released

### ISSUE THREAD

**Issue by silviucc** [negativo17/nvidia-driver#112]
Hello,

It seems nvidia is confident enough to release this version as being stable.

Includes support for some new GPUs, bug fixes for wayland support, an important fix for Doom Eternal on Gnome desktops and a bugfix for people running Far Cry 5 with DXVK

**Comment by idarlund** [comment]
470.57.02 is released to production branch:
https://www.nvidia.com/Download/driverResults.aspx/177145/en-us

**Comment by scaronni** [comment]
Coming in a few hours.
