### ISSUE TITLE
when is repo updated

### ISSUE THREAD

**Issue by idarlund** [negativo17/nvidia-driver#114]
Hi,

Now that spec files are updated to the 470 driver. How long time will it take for the repos at https://negativo17.org/repos/nvidia/ to get the new rpms?

**Comment by scaronni** [comment]
There is an issue with the 470 branch of drivers. CUDA ships the `libnvvm.so.4` library and the drivers ship `libnvidia-nvvm.so.4.0.0` with a shared name of `libnvvm.so.4` again. Aything triggering `ldconfig` creates the symlink and it conflicts with the library from CUDA.

I'm trying to figure out if the driver library replaces the CUDA provided one.

**Comment by scaronni** [comment]
I think i've come up with the right solution, packages will be uploaded soon.
