### ISSUE TITLE
New releases available - fix for displays with variable refresh rates

### ISSUE THREAD

**Issue by silviucc** [negativo17/nvidia-driver#115]
Hello.

Versions 495.44 and 470.82.00 are available. Both have the fix for issues caused for those that use displays with variable refresh rates.

**Comment by kmare** [comment]
Would be great to see the 495.44 release in negativo17, as it finally adds proper Wayland support for nvidia cards!

**Comment by scaronni** [comment]
I'm pushing 470.82 while working on 495.44.

**Comment by silviucc** [comment]
That's great news! Thank you :)

**Comment by scaronni** [comment]
Pushed 470.82 and new CUDA stuff.

**Comment by scaronni** [comment]
Pushing 495.44 right now.
