### ISSUE TITLE
Fedora 25 fails to start with kernel 4.9.3

### ISSUE THREAD

**Issue by RedDwarf69** [negativo17/nvidia-driver#12]
With the recent 4.9.3 kernel update my system fails to get into GDM any more (it keep working if booting from 4.8.16). Sorry, not sure what logs to attach.

$ rpm -qa | grep -e nvidia -e kernel-4 | sort
akmod-nvidia-340.101-1.fc25.x86_64
kernel-4.8.15-300.fc25.x86_64
kernel-4.8.16-300.fc25.x86_64
kernel-4.9.3-200.fc25.x86_64
kmod-nvidia-4.8.15-300.fc25.x86_64-340.101-1.fc25.x86_64
kmod-nvidia-4.8.16-300.fc25.x86_64-340.101-1.fc25.x86_64
kmod-nvidia-4.9.3-200.fc25.x86_64-340.101-1.fc25.x86_64
nvidia-driver-340.101-1.fc25.x86_64
nvidia-driver-libs-340.101-1.fc25.x86_64
nvidia-libXNVCtrl-340.101-1.fc25.x86_64
nvidia-settings-340.101-1.fc25.x86_64

$ lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation G98 [Quadro NVS 295] (rev a1)

**Comment by scaronni** [comment]
Sorry for the late reply, a patch was included for kernel 4.9 some time ago.
