### ISSUE TITLE
Weird corruption/misrendering in games with 530.41

### ISSUE THREAD

**Issue by dvdmuckle** [negativo17/nvidia-driver#139]
I've been having issues with the latest driver (530.41) in some games running through Proton. I've tested this with the same driver version from rpmfusion and those seem to work fine, so I'm opening an issue here. I'm not sure how that could make a difference but it's the only change I've made that fixed the issue. This is with Fedora 37 on a machine with both an RTX 3070ti and a mobile 1650. Example of the bug attached
![Screenshot from 2023-03-22 22-30-12](https://media.discordapp.net/attachments/351570050714697730/1090429973023703091/image.png?width=810&height=456)

**Comment by dvdmuckle** [comment]
My mistake, this looks to happen with the RPMFusion version too. I guess this must be a bug with this driver...? Or perhaps to do with shaders. Either way, closing this issue.

**Comment by leigh123linux** [comment]
Maybe it's a steam issue.

https://bugzilla.rpmfusion.org/show_bug.cgi?id=6615

**Comment by dvdmuckle** [comment]
Hm, that sounds like it might be the case. I'm hearing from some folks that the 530 driver itself might not be in great shape, but I can't find any specific issue or bug filed.
