### ISSUE TITLE
Is version 535.54.03 already available at the repo?

### ISSUE THREAD

**Issue by msmafra** [negativo17/nvidia-driver#142]
Hello there.
I'm/I was only using DNF5, so I thought it could be the problem with it, but running DNF4 it also did not update even cleaning the cache.

**Comment by msmafra** [comment]
"It's alive!"
![Captura de tela de 2023-06-21 10-33-35](https://github.com/negativo17/nvidia-driver/assets/1005457/12d44119-4458-4c4b-834b-b100193c2a90)
Thanks!

**Comment by scaronni** [comment]
It depends on how busy I am and if the release requires some testing (in this case the pkcs libraries compiled for OpenSSL 1.1 OR 3.0). Cheers.
