### ISSUE TITLE
545.29.06 Linux Driver fix update 

### ISSUE THREAD

**Issue by DimPaDev** [negativo17/nvidia-driver#147]
Just wanted to let you know that NVIDIA  545.29.06 Linux Driver was released today! it may fix some issues and regressions. 

Thank you very much for providing this great repo and keep up the great work!

@scaronni

**Comment by scaronni** [comment]
Ongoing! Thanks.

**Comment by scaronni** [comment]
Talked too soon, the open source components have not been yet released:

- https://github.com/NVIDIA/nvidia-modprobe/tags
- https://github.com/NVIDIA/nvidia-persistenced/tags
- https://github.com/NVIDIA/nvidia-settings/tags
- https://github.com/NVIDIA/nvidia-xconfig/tags

**Comment by scaronni** [comment]
Usually those are available once the announcement is done at this page: https://forums.developer.nvidia.com/c/gpu-graphics/announcements-and-news/146

**Comment by scaronni** [comment]
> Talked too soon, the open source components have not been yet released:
> 
> - https://github.com/NVIDIA/nvidia-modprobe/tags
> - https://github.com/NVIDIA/nvidia-persistenced/tags
> - https://github.com/NVIDIA/nvidia-settings/tags
> - https://github.com/NVIDIA/nvidia-xconfig/tags

Nope, these above.

**Comment by kmare** [comment]
Thanks @scaronni !

**Comment by msmafra** [comment]
Fixed for me with 545.29.06. Thanks @scaronni .
