### ISSUE TITLE
New driver release : 550.54.14

### ISSUE THREAD

**Issue by DimPaDev** [negativo17/nvidia-driver#152]
Would you mind sparing a moment to update the Nvidia drivers in the repository? The latest release, version 550.54.14, appears to bring forth some interesting bug fixes.

[Release highlights since 550.40.07](https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-550-54-14-production-branch-release/283925)

- Fixed a bug that caused HDMI FRL displays to flicker or blank when enabling VRR with 8 bits per color channel.
- Fixed a regression introduced with the 550.40.07 beta driver which caused corrupted window decorations in some applications when running on GNOME.
- Fixed a bug where vkAcquireNextImageKHR() was not returning VK_ERROR_OUT_OF_DATE_KHR when it should with WSI X11 swapchains.
- Fixed a bug where fences passed to VkSwapchainPresentFenceInfoEXT could signal earlier than expected when a WSI X11 swap chain becomes out of date.
- Fixed Xid errors on Hogwarts Legacy and Forza Horizon 4.
- Added support for the VK_KHR_video_encode_queue, VK_KHR_video_encode_h264, VK_KHR_video_encode_h265 and VK_KHR_video_maintenance1 extensions.
- Fixed a regression which prevented some Vulkan applications from receiving VK_DEVICE_LOST upon a VT switch, which could lead to the application hanging or behaving incorrectly.
- Fixed a bug that prevented nvidia-installer from honoring the --gbm-backend-dir command line option.

@scaronni

**Comment by kmare** [comment]
Seems like also the open source modules were updated:

https://github.com/NVIDIA/nvidia-modprobe/tags
https://github.com/NVIDIA/nvidia-persistenced/tags
https://github.com/NVIDIA/nvidia-settings/
https://github.com/NVIDIA/nvidia-xconfig/tags

**Comment by kmare** [comment]
Take your time Simone and enjoy!

**Comment by msmafra** [comment]
> Would you mind sparing a moment to update the Nvidia drivers in the repository? The latest release, version 550.54.14, appears to bring forth some interesting bug fixes.
> 
> [Release highlights since 550.40.07](https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-550-54-14-production-branch-release/283925)
> 
> * Fixed a bug that caused HDMI FRL displays to flicker or blank when enabling VRR with 8 bits per color channel.
> * Fixed a regression introduced with the 550.40.07 beta driver which caused corrupted window decorations in some applications when running on GNOME.
> * Fixed a bug where vkAcquireNextImageKHR() was not returning VK_ERROR_OUT_OF_DATE_KHR when it should with WSI X11 swapchains.
> * Fixed a bug where fences passed to VkSwapchainPresentFenceInfoEXT could signal earlier than expected when a WSI X11 swap chain becomes out of date.
> * Fixed Xid errors on Hogwarts Legacy and Forza Horizon 4.
> * Added support for the VK_KHR_video_encode_queue, VK_KHR_video_encode_h264, VK_KHR_video_encode_h265 and VK_KHR_video_maintenance1 extensions.
> * Fixed a regression which prevented some Vulkan applications from receiving VK_DEVICE_LOST upon a VT switch, which could lead to the application hanging or behaving incorrectly.
> * Fixed a bug that prevented nvidia-installer from honoring the --gbm-backend-dir command line option.
> 
> @scaronni

Worth the warning:
https://www.gamingonlinux.com/2024/02/nvidia-disclose-new-driver-security-issues-feb-28/

**Comment by scaronni** [comment]
Almost done, all the other packages except `nvidia-kmod-common` are ok (you can check the git repos). For `nvidia-kmod-common` I need to finish this one: https://github.com/negativo17/nvidia-kmod-common/issues/12

**Comment by scaronni** [comment]
Moved finishing that to a later step.
