### ISSUE TITLE
eglinfo segmentation fault with 550.54.14

### ISSUE THREAD

**Issue by vpxyz** [negativo17/nvidia-driver#153]
Hi Simone, 
with the latest driver eglinfo crash:
....
    GL_OES_texture_npot, GL_OES_texture_stencil8, 
    GL_OES_texture_storage_multisample_2d_array, GL_OES_texture_view, 
    GL_OES_vertex_array_object, GL_OES_vertex_half_float, 
    GL_OES_viewport_array, GL_OVR_multiview, GL_OVR_multiview2
corrupted size vs. prev_size
Annullato (core dump creato)

It seem related to this issue https://github.com/NVIDIA/egl-wayland/issues/93 , closed as solved with `egl-gbm-1.1.0-5`
https://github.com/NVIDIA/egl-wayland/issues/93#issuecomment-1822501099

Thank you

**Comment by leigh123linux** [comment]
Update egl-gbm, it's currently in updates-testing

https://bodhi.fedoraproject.org/users/leigh123linux

negativo17 repo is responsible for this issue, they decided to epoch the official package.
