### ISSUE TITLE
is there a way to downgrade to 545, cuda 12.3 and cuddn 8.9?

### ISSUE THREAD

**Issue by realKarthikNair** [negativo17/nvidia-driver#154]
Tensorflow doesnt even have expiremental support for cuda 12.4 and cuddn 9.x

![image](https://github.com/negativo17/nvidia-driver/assets/78267371/9240fbad-a2b7-455f-a934-075af843b19c)

So is there a way I can go back to 545, cuda 12.3 and cuddn 8.9 from negativo17 repo?

I checked https://negativo17.org/repos/nvidia/ but couldnt find older drivers there

**Comment by scaronni** [comment]
Unfortunately not. I don't have time/capacity/hardware necessary to maintain multiple branches. Please use Nvidia's own repositories.
