### ISSUE TITLE
nvidia-powerd being enabled on unsuppoted GPUs

### ISSUE THREAD

**Issue by msmafra** [negativo17/nvidia-driver#159]
Hello there

The File 70-nvidia.preset is enabling nvidia-powerd.service by default, but that service, based on the [NVIDIA documentation](https://download.nvidia.com/XFree86/Linux-x86_64/560.35.03/README/dynamicboost.html), should only be enabled for Ampere and up architectures. 

![Captura de tela de 2024-08-27 10-57-11](https://github.com/user-attachments/assets/d5c269bc-dfff-4ce1-92ff-c5375b704f7f)

```
# Enable complete power management. From:
# file:///usr/share/doc/nvidia-driver/html/powermanagement.html

enable nvidia-hibernate.service
enable nvidia-resume.service
enable nvidia-suspend.service


# Enable Dynamic Boost. From:
# file:///usr/share/doc/nvidia-driver/html/dynamicboost.html

enable nvidia-powerd.service
```
On my machine with a Turing GPU (RTX 2060 mobile) it was enabled since 560.35.03, it seems. I'm asuming it's just that is causing a return-from-suspend glitch where I would have to type my password 3-5 times because it keeps suspending again while I'm typying my password or after I'm already using my workspace/desktop on Gnome. 
Even not being it causing that problem, it should only be enable by default, following NVIDIA's documentation, if the GPu is from Ampere or newer.

**Comment by scaronni** [comment]
`powerd` (DynamicBoost) has nothing to do with what you are experiencing.

You're correct in saying that the daemon should only be enabled in a subset of hardware combinations, but if the daemon starts on a system without DynamicBoost enabled, it just exists wtihout doing anything, like in your screenshot ("Deactivated succesfully"), so it's safe to leave enabled (it's the "-" in the command line of the `systemd` unit that makes it exit gracefully).

Besides that, as described in the manual that you linked, `powerd` controls the behaviour of DynamicBoost, not the suspend/resume cycle.
