### ISSUE TITLE
nvidia-driver-cuda-375.39-2.el7.x86_64 missing dependency

### ISSUE THREAD

**Issue by welbers** [negativo17/nvidia-driver#17]
Under the current CentOS7 your latest nvidia-driver has a missing dependency and won't install.
Missing dependency: opencl-filesystem
There's such a package for Fedora but not for Redhat/CentOS.

Here the message from "yum update":
# env LANGUAGE=en_US.UTF-8 yum update
Skipping filters plugin, no data
--> Running transaction check
---> Package nvidia-driver.x86_64 2:375.39-1.el7 will be updated
---> Package nvidia-driver.x86_64 2:375.39-2.el7 will be an update
---> Package nvidia-driver-NVML.x86_64 2:375.39-1.el7 will be updated
---> Package nvidia-driver-NVML.x86_64 2:375.39-2.el7 will be an update
---> Package nvidia-driver-cuda.x86_64 2:375.39-1.el7 will be updated
---> Package nvidia-driver-cuda.x86_64 2:375.39-2.el7 will be an update
--> Processing Dependency: ocl-icd for package: 2:nvidia-driver-cuda-375.39-2.el7.x86_64
--> Processing Dependency: opencl-filesystem for package: 2:nvidia-driver-cuda-375.39-2.el7.x86_64
---> Package nvidia-driver-cuda-libs.x86_64 2:375.39-1.el7 will be updated
---> Package nvidia-driver-cuda-libs.x86_64 2:375.39-2.el7 will be an update
---> Package nvidia-driver-libs.x86_64 2:375.39-1.el7 will be updated
---> Package nvidia-driver-libs.x86_64 2:375.39-2.el7 will be an update
--> Running transaction check
---> Package nvidia-driver-cuda.x86_64 2:375.39-2.el7 will be an update
--> Processing Dependency: opencl-filesystem for package: 2:nvidia-driver-cuda-375.39-2.el7.x86_64
---> Package ocl-icd.x86_64 0:2.2.11-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 2:nvidia-driver-cuda-375.39-2.el7.x86_64 (epel-nvidia)
           Requires: opencl-filesystem

**Comment by scaronni** [comment]
I've requested the branch creation for both EPEL 6 & 7, but I forgot to push the package in the repository in the meanwhile the request will get approved:

https://admin.fedoraproject.org/pkgdb/package/rpms/opencl-filesystem/

I will resync the repository in a few minutes.
