### ISSUE TITLE
Make nvidia-driver depend on nvidia-driver-libs.i686

### ISSUE THREAD

**Issue by AlexanderVL** [negativo17/nvidia-driver#2]
Last night I installed the nvidia-driver package on a fresh 64-bit Fedora 24, but it didn't install the 32-bit version of the nvidia-driver-libs package. The 32-bit version of this package is needed for Steam, without it Steam refuses to start. Can you please add a dependency on nvidia-driver-libs.i686 to the nvidia-driver package?

**Comment by scaronni** [comment]
No sorry, there are a lot of people who are not interested on having 32 bit libraries on a 64 bit system. Not everyone plays Steam games :)

**Comment by scaronni** [comment]
Btw, It's already written in the instructions that they are needed for 32 bit applications and how to install them.
