### ISSUE TITLE
Please add nvidia-driver rpm for Rawhide please!

### ISSUE THREAD

**Issue by kuboosoft** [negativo17/nvidia-driver#22]
Hi, can you maintain the package for Rawhide, please ;) 
thanks :)

**Comment by scaronni** [comment]
Sorry, not at the moment. The Nvidia kernel modules work only for released kernel versions, and require patches for newer unreleased kernels that are not always available. Also, if there's an X.org ABI change, X driver follows the same approach for the kernel and is available only for released X servers in binary format; so there's a high chance that it does not work at all.

When a release is approaching, I normally build also for that. That's the maximum I can do at the moment, sorry.

**Comment by kuboosoft** [comment]
thanks @scaronni
