### ISSUE TITLE
gstreamer-plugins-bad-free conflicts

### ISSUE THREAD

**Issue by zwgraham** [negativo17/nvidia-driver#35]
I recently did a fresh F26 installation and decided to try using your nvidia package instead of RPMFusion's. 

I went ahead and added the multimedia and steam repositories, with no issues, but when running a check-upate I've noticed a package conflict. 

dnf output is in the fedora pastebin here: https://paste.fedoraproject.org/paste/zSj9RFoO09qjjvYRt2ZynQ

I'm not to keen on package-conflict debugging, but let me know if there's any diagnostics I can do to help solve this.

**Comment by scaronni** [comment]
The multimedia repository is not compatible with RPMFusion, sorry: https://negativo17.org/multimedia/
