### ISSUE TITLE
Clock modification disabled (set to read-only) on driver 837

### ISSUE THREAD

**Issue by egee-irl** [negativo17/nvidia-driver#36]
The latest Nvidia driver version appears to disable overclocking via Coolbits.

Both core & memory clocks are restricted to Read-Only mode. I confirmed that the previous driver version 384 does not have this issue.

My card is an ASUS GTX 760

**Comment by scaronni** [comment]
You should open a bug to Nvidia on their forum; I'm merely packaging the various components:

https://devtalk.nvidia.com/default/board/98/linux/
