### ISSUE TITLE
Steam via flatpak stop working after upgrading nvidia driver from 387.34 -> 390.12

### ISSUE THREAD

**Issue by rabin-io** [negativo17/nvidia-driver#40]
Hi, not sure if it's the right place to open this issue, 

I'm using F27 and running Steam via the flatpak (from [here](https://flathub.org/apps.html))
after the upgrade to 390 steam client won't show up and will hang in the background.
downgrading the packages, resolved the problem.

    dnf downgrade -y dkms-nvidia nvidia-driver nvidia-driver-libs nvidia-driver-libs nvidia-libXNVCtrl nvidia-settings

please let me know, if there is anything else I can provide to debug this problem.

**Comment by scaronni** [comment]
Sorry, too many changes since then. Reopen if still occurring.

**Comment by scaronni** [comment]
Sorry, too many changes since then. Reopen if still occurring.
