### ISSUE TITLE
Epoc update

### ISSUE THREAD

**Issue by amavlyanov** [negativo17/nvidia-driver#47]
Please update Epoch version in all your nvidia packages from 2 to 3 since it conflicts with rpmfusion's packages (they moved to the Epoch 3 some time in the past).

**Comment by leigh123linux** [comment]
@scaronni We raised the epoch because cuda repo added an alien nvidia package version (390.30)

http://www.nvidia.com/download/driverResults.aspx/131164/en-us

**Comment by scaronni** [comment]
Thanks I will change it so they can co-exist.

**Comment by scaronni** [comment]
Pushing packages now.
