### ISSUE TITLE
NVidia Driver for EL7.5?

### ISSUE THREAD

**Issue by juxi500** [negativo17/nvidia-driver#52]
Hello,

Is there any chance for building NVidia Driver for EL7.5? (RHEL 7.5 is released and CentOS is already in CR Repo)

Thank you very much and have a nice day :)

**Comment by scaronni** [comment]
Hello, pushed yesterday along with other updates.

**Comment by juxi500** [comment]
Thank you very much Simone, you are great, it is working flawlessly :)

**Comment by scaronni** [comment]
BTW you can use DKMS until the module is available. I plan to also add the `akmod-nvidia` variant as well, as `akmods` is now in the main Fedora repositories also for CentOS/RHEL.
