### ISSUE TITLE
kmod-nvidia for el7.6

### ISSUE THREAD

**Issue by juxi500** [negativo17/nvidia-driver#66]
Hello,

Is there any chance for building NVidia Driver for EL7.6? (RHEL 7.6 is released and CentOS is already in CR Repo)

Thank you very much and have a nice day :)

**Comment by scaronni** [comment]
Building it.

**Comment by juxi500** [comment]
Thank you very much Simone, you are great, looking forward to test it, I will let you know how does it work :)

P.S.: some people report having broken icons inside Gnome desktop environment after the update to 7.6, so don't forget to backup your system first :)

Have a nice day

**Comment by juxi500** [comment]
seems working flawlessly, thank you very much! :)
