### ISSUE TITLE
nvidia-driver-410 (long-lived branch) missing from Fedora 28

### ISSUE THREAD

**Issue by michel-slm** [negativo17/nvidia-driver#67]
Per https://negativo17.org/nvidia-driver/ the long-lived drivers are supposed to be available on Fedora 28. But looking at https://negativo17.org/repos/nvidia/fedora-28/x86_64/, while dkms-nvidia is available for version 410, and some other packages (like nvidia-persistenced, nvidia-settings and nvidia-xconfig) are, nvidia-driver* packages are only available from the short-lived (v415) branch.

**Comment by scaronni** [comment]
Sorry for the late reply. The supported list is in order of priority. Ergo, Fedora will always get the short lived branch and RHEL/CentOS will always have the long lived branch as maximum. Rawhide/branched will always get the beta release (418.30 coming soon).
