### ISSUE TITLE
Unnecessary path in ld.so.conf?

### ISSUE THREAD

**Issue by iavael** [negativo17/nvidia-driver#7]
Since libglvnd (with it's own proxy libGL and friends) is required anyway, why not remove these lines from specfile?

```sh
# Library search path
echo "%{_libdir}/nvidia" > %{buildroot}%{_sysconfdir}/ld.so.conf.d/nvidia-%{_lib}.conf
```

**Comment by scaronni** [comment]
It's still required in `nvidia-driver-cuda-libs` for the OpenCL library:

https://github.com/negativo17/nvidia-driver/blob/master/nvidia-driver.spec#L422-L424

But in `nvidia-driver-libs` should not actually be there, it's a leftover:

https://github.com/negativo17/nvidia-driver/blob/master/nvidia-driver.spec#L406

I've removed it from the spec file, will trigger a new rebuild soon.

**Comment by scaronni** [comment]
https://github.com/negativo17/nvidia-driver/commit/f2c5f01d4f2c05e512e79eb8a89f5ed77114d1f0
