### ISSUE TITLE
fedora 29 build driver 418.56 for kernel 5.0.* fails

### ISSUE THREAD

**Issue by joshuaandrews63** [negativo17/nvidia-driver#76]
DKMS make.log for nvidia-418.56 for kernel 5.0.4-200.fc29.x86_64 (x86_64)
Mon Apr  1 06:52:14 PDT 2019
make[1]: Entering directory '/usr/src/kernels/5.0.4-200.fc29.x86_64'
  SYMLINK /var/lib/dkms/nvidia/418.56/build/nvidia/nv-kernel.o
  SYMLINK /var/lib/dkms/nvidia/418.56/build/nvidia-modeset/nv-modeset-kernel.o
  CC [M]  /var/lib/dkms/nvidia/418.56/build/nvidia/nv-frontend.o
  CC [M]  /var/lib/dkms/nvidia/418.56/build/nvidia/nv-instance.o
In file included from /var/lib/dkms/nvidia/418.56/build/nvidia/nv-instance.c:13:
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h: In function ‘nv_dma_maps_swiotlb’:
In file included from /var/lib/dkms/nvidia/418.56/build/nvidia/nv-frontend.c:13:
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h: In function ‘nv_dma_maps_swiotlb’:
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h:1287:31: error: ‘swiotlb_dma_ops’ undeclared (first use in this function); did you mean ‘swiotlb_map’?
     swiotlb_in_use = (ops == &swiotlb_dma_ops);
                               ^~~~~~~~~~~~~~~
                               swiotlb_map
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h:1287:31: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h:1287:31: error: ‘swiotlb_dma_ops’ undeclared (first use in this function); did you mean ‘swiotlb_map’?
     swiotlb_in_use = (ops == &swiotlb_dma_ops);
                               ^~~~~~~~~~~~~~~
                               swiotlb_map
/var/lib/dkms/nvidia/418.56/build/common/inc/nv-linux.h:1287:31: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:277: /var/lib/dkms/nvidia/418.56/build/nvidia/nv-instance.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:277: /var/lib/dkms/nvidia/418.56/build/nvidia/nv-frontend.o] Error 1
make[1]: *** [Makefile:1557: _module_/var/lib/dkms/nvidia/418.56/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.0.4-200.fc29.x86_64'
make: *** [Makefile:79: modules] Error 2

**Comment by scaronni** [comment]
Driver has been updated since then.
