### ISSUE TITLE
Conflicting package

### ISSUE THREAD

**Issue by pentatonicfunk** [negativo17/nvidia-driver#83]
```package nvidia-driver-3:435.21-1.fc30.x86_64 conflicts with xorg-x11-drv-nvidia provided by xorg-x11-drv-nvidia-3:430.40-1.fc30.x86_64```

**Comment by scaronni** [comment]
That is correct, you can not install them at the same time, and this repository and RPMFusion are not compatible. If you want to use RPMFusion, remove the one providing this driver.

https://negativo17.org/nvidia-driver/
