### ISSUE TITLE
nvidia-settings requires older version of nvidia-driver el8

### ISSUE THREAD

**Issue by jeffclay** [negativo17/nvidia-driver#91]
Attempting to install nvidia-settings on RHEL 8 fails.

"nothing provides nvidia-driver(x86-64) = 3:430.40 needed by nvidia-settings-3:430.40-1.el8.x86_64"

The only version of nvidia-driver in https://negativo17.org/repos/nvidia/epel-8/x86_64/ is "nvidia-driver-435.21-2.el8.x86_64.rpm"

**Comment by scaronni** [comment]
New packages online soon. I was not absolutely finished with RHEL/CentOS 8.
