### ISSUE TITLE
Magic is not identical to kernel version

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [negativo17/nvidia-driver#97]
Hi,
Thanks so much for your work on this repo.  It makes the life of a non-developer using Linux so much better.

I upgraded to Fedora 31 today, and the nvidia driver did not follow the journey with me.  The first hint was that the kernel module wasn't loaded.  Trying to load the module resulted in 
````
could not insert 'nvidia': Exec format error
````
dmesg reported
````
nvidia: version magic '5.4.18-100.fc30.x86_64 SMP mod_unload ' should be '5.4.18-200.fc31.x86_64 SMP mod_unload '
````
Note the -100 vs -200.

The solution was found here: https://forums.fedoraforum.org/showthread.php?323196-Nvidia-version-magic-wrong-Kernel&p=1831168#post1831168
The version of the kernel differs, but the problem and its solution fit perfectly.

I don't know if it's a Fedora, kernel, nVidia, other repo, or your packages causing the error, but wanted to bring it to your attention to see if you can work around it.  I think this may cause pain to a large number of people.

**Comment by scaronni** [comment]
Hi, thanks for the heads up.

Can you check if by chance you have both akmods and dkms installed? If so, please remove the package `dkms`. That is the one putting the files in the `weak-udpates` folder.

If you have an account on fedoraforum.org, please post the information there as well.

Thanks.
