### ISSUE TITLE
440.82 release - kernel 5.6 fixes

### ISSUE THREAD

**Issue by kmare** [negativo17/nvidia-driver#98]
@scaronni A new version of the driver was released, fixing a few 5.6 compatibility issues (I hope this is the right place to remind about it). Thank you!

https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-440-82-long-lived-branch-release/118864
https://www.nvidia.co.uk/Download/driverResults.aspx/159370/en-uk

**Comment by scaronni** [comment]
Yes sure! Packages will be online later today. Thanks.

**Comment by scaronni** [comment]
A bit busy sorry, pushing the packages now.
