### ISSUE TITLE
problem using yum and negativo17/nvidia repository

### ISSUE THREAD

**Issue by brunckodusan** [negativo17/nvidia-driver#99]
Hello,

I have problem connected with the use negativo17/nvidia repository with yum. Practically I cannot use this repo due too long time for connection. The same I see when I am using e.g. browser, but in this case the response is also long but acceptable...

Please, be so kind and look on this issue.

Thank you very much in advance.

Regards,
                    Dusan

**Comment by scaronni** [comment]
Closed with the server move.
